on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    # - name: Install Wine
    #   run: |
    #     sudo dpkg --add-architecture i386
    #     sudo apt update
    #     sudo apt install -y wine64 wine32
    - name: Install Yarn
      run: |
        npm install -y -g yarn
    - name: Run Clean
      run: yarn run clean
    - name: Install dependencies
      run: yarn install
    - name: Electron Build and Package
      run: yarn run package
    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: package
    - name: Upload Dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
    - name: Send Email Notification
      if: always()
      uses: dawidd6/action-send-mail@v3.12.0
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        to: omac12631@gmail.com
        from: GitHub Actions
        body: |
          ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}.
          Build URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          Repository URL: ${{ github.repositoryUrl }} 
          Actor: ${{ github.actor }} 
          Commit Message: ${{ github.event.head_commit.message }}
