on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build Electron app
      run: npm run build
    - name: Upload Dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
    - name: Get workflow run URL
      id: get_url
      run: echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    - name: Set build status
      id: build_status
      run: |
        if [ ${{ job.status }} == "success" ]; then
          echo "Build succeeded"
        else
          echo "Build failed"
        fi
    - name: Send notification
      run: |
        echo "Build Status: ${{ steps.build_status.outputs.stdout }}"
        echo "Build URL: ${{ steps.get_url.outputs.stdout }}"
