on:
  push:
    branches:
      - main

jobs:
  check_vulnerabilities:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      - name: Check for vulnerabilities
        run: |
          audit_result=$(npm audit --json)
          vulnerabilities=$(echo "$audit_result" | jq -r '.vulnerabilities | to_entries[] | select(.value.severity == "high" or .value.severity == "critical") | "\(.key) (\(.value.severity))"')
          if [ -n "$vulnerabilities" ]; then
              echo "High or critical vulnerabilities found:"
              echo "$vulnerabilities"
              exit 1
          else
              echo "No high or critical vulnerabilities found."
          fi

